### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/embedded-gremlin#2]
Need to be able to run CI that will test against text-extension-for-pandas. Currently the `.travis.yml` file exists and should work to install text-extension-for-pandas to Travis, it just needs to be activated to run.

**Comment by frreiss** [comment]
The repository was private. I've made it public. Can you try again, please, @BryanCutler ?

**Comment by BryanCutler** [comment]
Yup, working now thanks @frreiss !
